version: '3.8'

services:
  # 1. The PostgreSQL Database (For Inventory)
  postgres:
    image: postgres:16-alpine
    container_name: aerolock-postgres
    restart: always
    environment:
      POSTGRES_USER: aerolock_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aerolock
    ports:
      - "5432:5432"
    volumes:
      # This saves your database data to your hard drive so it doesn't get deleted when the container stops
      - postgres_data:/var/lib/postgresql/data

  # 2. The Redis Cache & Lock Manager
  redis:
    image: redis:7-alpine
    container_name: aerolock-redis
    restart: always
    ports:
      - "6379:6379"
    # We pass a custom command to make Redis persist its data to disk
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

# Define the persistent volumes
volumes:
  postgres_data:
  redis_data: