apiVersion: v1
kind: Secret
metadata:
  name: aerolock-secrets
  labels:
    app: aerolock
type: Opaque
data:
  # Base64 encoded secrets
  # aerolock_user
  POSTGRES_USER: "YWVyb2xvY2tfdXNlcg==" 
  # password123
  POSTGRES_PASSWORD: "cGFzc3dvcmQxMjM="
  # postgresql+asyncpg://aerolock_user:password123@postgres:5432/aerolock
  DATABASE_URL: "cG9zdGdyZXNxbCthc3luY3BnOi8vYWVyb2xvY2tfdXNlcjpwYXNzd29yZDEyM0Bwb3N0Z3Jlczo1NDMyL2Flcm9sb2Nr"
  # redis://redis:6379/0
  REDIS_URL: "cmVkaXM6Ly9yZWRpczo2Mzc5LzA="
